"use client";

import { useState } from "react";
import { useShop } from "../providers";
import { formatPrice, type Product } from "../../lib/catalog";

const blankProduct = { title: "", author: "", price: "", salePrice: "", category: "ไพ่ทาโรต์", stock: "", description: "", coupon: "", images: "", symbol: "☾", color: "violet" };

export default function AdminPage() {
  const { products, articles, coupons, orders, addProduct, updateProduct, addArticle, addCoupon } = useShop();
  const [tab, setTab] = useState<"products" | "articles" | "coupons">("products"); const [editorOpen, setEditorOpen] = useState(false); const [editingId, setEditingId] = useState<string | null>(null); const [draft, setDraft] = useState(blankProduct); const [articleOpen, setArticleOpen] = useState(false); const [couponOpen, setCouponOpen] = useState(false);
  const field = (name: keyof typeof blankProduct, value: string) => setDraft((current) => ({ ...current, [name]: value }));
  const openProduct = (product?: Product) => { setEditingId(product?.id || null); setDraft(product ? { title: product.title, author: product.author, price: String(product.price), salePrice: String(product.salePrice || ""), category: product.category, stock: String(product.stock), description: product.description, coupon: product.coupon || "", images: product.images?.join(", ") || "", symbol: product.symbol, color: product.color } : blankProduct); setEditorOpen(true); };
  const saveProduct = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const value: Product = { id: editingId || `${draft.title.toLowerCase().replace(/[^a-z0-9ก-๙]+/g, "-")}-${Date.now().toString().slice(-4)}`, title: draft.title, author: draft.author, price: Number(draft.price), salePrice: draft.salePrice ? Number(draft.salePrice) : undefined, category: draft.category as Product["category"], stock: Number(draft.stock), description: draft.description, coupon: draft.coupon || undefined, images: draft.images.split(",").map((image) => image.trim()).filter(Boolean), symbol: draft.symbol, color: draft.color as Product["color"], badge: draft.salePrice ? "ลดราคา" : undefined }; editingId ? updateProduct(value) : addProduct(value); setEditorOpen(false); };
  const revenue = orders.reduce((sum, order) => sum + order.total, 0);
  return <main className="admin-page"><aside className="admin-sidebar"><div className="admin-brand"><span>A</span><b>ARCANA<small>ADMIN SPACE</small></b></div><nav><button className={tab === "products" ? "active" : ""} onClick={() => setTab("products")}><span>◇</span> สินค้า</button><button className={tab === "articles" ? "active" : ""} onClick={() => setTab("articles")}><span>▤</span> บทความ</button><button className={tab === "coupons" ? "active" : ""} onClick={() => setTab("coupons")}><span>％</span> คูปอง</button></nav><a href="/">← กลับหน้าร้าน</a></aside>
    <section className="admin-content"><header className="admin-top"><div><p>แดชบอร์ดผู้ดูแล</p><h1>สวัสดี, ARCANA</h1></div><span className="admin-avatar">A</span></header><div className="admin-stats"><article><span>สินค้าทั้งหมด</span><b>{products.length}</b><small>รายการในร้าน</small></article><article><span>คำสั่งซื้อ</span><b>{orders.length}</b><small>รายการทั้งหมด</small></article><article><span>ยอดขายจำลอง</span><b>{formatPrice(revenue)}</b><small>จากคำสั่งซื้อในเครื่องนี้</small></article><article><span>บทความ</span><b>{articles.length}</b><small>เผยแพร่และฉบับร่าง</small></article></div>
      {tab === "products" && <div className="admin-section"><div className="admin-section-head"><div><h2>จัดการสินค้า</h2><p>เพิ่มสินค้า แก้ราคา โปรโมชัน คลัง และรายละเอียด</p></div><button onClick={() => openProduct()}>＋ เพิ่มสินค้าใหม่</button></div><div className="admin-table"><div className="admin-tr admin-th"><span>สินค้า</span><span>หมวดหมู่</span><span>ราคา</span><span>สต็อก</span><span /></div>{products.map((product) => <div className="admin-tr" key={product.id}><span className="admin-product"><i className={product.color}>{product.symbol}</i><b>{product.title}<small>{product.author}</small></b></span><span>{product.category}</span><span>{product.salePrice ? <><del>{formatPrice(product.price)}</del><b>{formatPrice(product.salePrice)}</b></> : formatPrice(product.price)}</span><span className={product.stock < 10 ? "low-stock" : ""}>{product.stock} ชิ้น</span><button onClick={() => openProduct(product)}>จัดการ</button></div>)}</div></div>}
      {tab === "articles" && <div className="admin-section"><div className="admin-section-head"><div><h2>บทความ SEO</h2><p>สร้างเนื้อหาเพื่อให้ลูกค้าค้นพบ ARCANA ได้ง่ายขึ้น</p></div><button onClick={() => setArticleOpen(true)}>＋ เขียนบทความ</button></div><div className="admin-cards">{articles.map((article) => <article key={article.slug}><i className={article.color}>{article.symbol}</i><div><span>{article.category} · {article.date}</span><h3>{article.title}</h3><p>{article.excerpt}</p></div><em>{article.status || "เผยแพร่"}</em></article>)}</div></div>}
      {tab === "coupons" && <div className="admin-section"><div className="admin-section-head"><div><h2>คูปองส่วนลด</h2><p>สร้างโค้ดส่วนลดสำหรับแคมเปญและสินค้า</p></div><button onClick={() => setCouponOpen(true)}>＋ สร้างคูปอง</button></div><div className="coupon-grid">{coupons.map((coupon) => <article key={coupon.code}><span>COUPON</span><h3>{coupon.code}</h3><b>ลด {coupon.discount}%</b><small className={coupon.active ? "active" : ""}>{coupon.active ? "กำลังใช้งาน" : "ปิดใช้งาน"}</small></article>)}</div></div>}
    </section>
    {editorOpen && <div className="modal-backdrop"><form className="admin-modal" onSubmit={saveProduct}><button type="button" className="modal-close" onClick={() => setEditorOpen(false)}>×</button><p className="eyebrow">PRODUCT EDITOR</p><h2>{editingId ? "แก้ไขสินค้า" : "เพิ่มสินค้าใหม่"}</h2><div className="admin-form-grid"><label>ชื่อสินค้า<input required value={draft.title} onChange={(event) => field("title", event.target.value)} /></label><label>ผู้เขียน<input required value={draft.author} onChange={(event) => field("author", event.target.value)} /></label><label>ราคาปก<input required min="0" type="number" value={draft.price} onChange={(event) => field("price", event.target.value)} /></label><label>ราคาขาย<input min="0" type="number" value={draft.salePrice} onChange={(event) => field("salePrice", event.target.value)} placeholder="ไม่ลดราคาให้เว้นว่าง" /></label><label>หมวดหมู่<select value={draft.category} onChange={(event) => field("category", event.target.value)}><option>ไพ่ทาโรต์</option><option>โหราศาสตร์</option><option>จิตวิญญาณ</option><option>พิธีกรรม</option></select></label><label>จำนวนสต็อก<input required min="0" type="number" value={draft.stock} onChange={(event) => field("stock", event.target.value)} /></label><label>คูปองที่ใช้ได้<input value={draft.coupon} onChange={(event) => field("coupon", event.target.value)} placeholder="เช่น MOON10" /></label><label>สัญลักษณ์ปก<input value={draft.symbol} onChange={(event) => field("symbol", event.target.value)} /></label><label className="full">รายละเอียดสินค้า<textarea required rows={4} value={draft.description} onChange={(event) => field("description", event.target.value)} /></label><label className="full">รูปภาพสินค้า<input value={draft.images} onChange={(event) => field("images", event.target.value)} placeholder="ชื่อหรือ URL รูปภาพ คั่นด้วยเครื่องหมายจุลภาค" /><span className="file-pick">＋ เลือกรูปจากเครื่อง<input type="file" accept="image/*" multiple onChange={(event) => field("images", [...(event.target.files || [])].map((file) => file.name).join(", "))} /></span></label></div><button className="admin-save">บันทึกสินค้า</button></form></div>}
    {articleOpen && <div className="modal-backdrop"><form className="admin-modal small" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const title = String(data.get("title")); addArticle({ slug: `${Date.now()}`, title, category: String(data.get("category")), excerpt: String(data.get("excerpt")), date: new Date().toLocaleDateString("th-TH", { day: "numeric", month: "long", year: "numeric" }), symbol: "✦", color: "violet", status: "ฉบับร่าง" }); setArticleOpen(false); }}><button type="button" className="modal-close" onClick={() => setArticleOpen(false)}>×</button><p className="eyebrow">SEO CONTENT</p><h2>สร้างบทความใหม่</h2><label>ชื่อบทความ<input name="title" required /></label><label>หมวดหมู่<input name="category" required placeholder="เช่น คู่มือทาโรต์" /></label><label>คำอธิบายสำหรับ SEO<textarea name="excerpt" required rows={4} /></label><button className="admin-save">บันทึกเป็นฉบับร่าง</button></form></div>}
    {couponOpen && <div className="modal-backdrop"><form className="admin-modal small" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); addCoupon({ code: String(data.get("code")).toUpperCase(), discount: Number(data.get("discount")), active: true }); setCouponOpen(false); }}><button type="button" className="modal-close" onClick={() => setCouponOpen(false)}>×</button><p className="eyebrow">PROMOTION</p><h2>สร้างคูปอง</h2><label>รหัสคูปอง<input name="code" required placeholder="เช่น STAR15" /></label><label>ส่วนลด (%)<input name="discount" required min="1" max="100" type="number" /></label><button className="admin-save">เปิดใช้คูปอง</button></form></div>}
  </main>;
}
