"use client";

import Link from "next/link";
import { useState } from "react";
import { useShop } from "../providers";
import { formatPrice } from "../../lib/catalog";
import { Icon } from "../../components/icon";

export default function CartPage() {
  const { cart, orders, updateQuantity, checkout } = useShop(); const [orderId, setOrderId] = useState<string | null>(null);
  const total = cart.reduce((sum, item) => sum + (item.salePrice || item.price) * item.quantity, 0); const shownOrder = orders.find((order) => order.id === orderId);
  return <main className="inner-page"><div className="page-intro compact"><p className="eyebrow">YOUR BAG</p><h1>ตะกร้าสินค้า</h1></div><section className="cart-page section">
    {cart.length ? <div className="cart-layout"><div className="cart-list">{cart.map((item) => <div className="cart-item" key={item.id}><div className={`cart-cover ${item.color}`}>{item.symbol}</div><div className="cart-item-info"><span>{item.category}</span><h2>{item.title}</h2><p>{item.author}</p><b>{formatPrice(item.salePrice || item.price)}</b></div><div className="quantity"><button onClick={() => updateQuantity(item.id, item.quantity - 1)}><Icon name="minus" /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)}><Icon name="plus" /></button></div><button className="remove" onClick={() => updateQuantity(item.id, 0)} aria-label="ลบสินค้า"><Icon name="trash" /></button></div>)}</div><aside className="order-summary"><h2>สรุปคำสั่งซื้อ</h2><div><span>ยอดรวมสินค้า</span><b>{formatPrice(total)}</b></div><div><span>ค่าจัดส่ง</span><b className="free">ฟรี</b></div><hr /><div className="total"><span>ยอดชำระทั้งหมด</span><strong>{formatPrice(total)}</strong></div><button className="pay-button" onClick={() => { const order = checkout(); setOrderId(order?.id || null); }}>ดำเนินการชำระเงิน <span>→</span></button><small>นี่คือหน้าชำระเงินแบบจำลอง ไม่มีการตัดเงินจริง</small></aside></div> : <div className="empty-state"><span>✦</span><h2>ตะกร้าของคุณยังว่าง</h2><p>เริ่มเลือกสำรับไพ่หรือหนังสือที่เรียกหาคุณได้เลย</p><Link href="/products" className="primary-button">เลือกดูสินค้า <span>→</span></Link></div>}
    {orders.length > 0 && <section className="purchases"><div className="purchase-heading"><div><p className="eyebrow">YOUR PURCHASES</p><h2>คำสั่งซื้อของคุณ</h2></div><Link href="/products">สร้างตะกร้าใหม่ <span>→</span></Link></div>{orders.map((order) => <button className={`purchase ${order.id === orderId ? "open" : ""}`} key={order.id} onClick={() => setOrderId(order.id)}><span><b>{order.id}</b><small>{order.createdAt} · {order.items.reduce((sum, item) => sum + item.quantity, 0)} รายการ</small></span><span className="status"><i />{order.status}</span><strong>{formatPrice(order.total)}</strong><span>›</span></button>)}</section>}
    {shownOrder && <div className="modal-backdrop" role="presentation" onClick={() => setOrderId(null)}><section className="payment-modal" role="dialog" aria-modal="true" aria-label="ชำระเงิน" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setOrderId(null)}>×</button><p className="eyebrow">ORDER {shownOrder.id}</p><h2>สแกน QR เพื่อชำระเงิน</h2><div className="mock-qr" aria-label="QR Code จำลอง"><span>ARCANA<br />PAY</span></div><strong>{formatPrice(shownOrder.total)}</strong><p className="payment-note">หลังชำระเงิน สถานะจะอัปเดตเป็น “กำลังตรวจสอบ” ในระบบจริง</p><div className="payment-status"><i /> รอชำระเงิน</div></section></div>}
  </section></main>;
}
