"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { ProductCard } from "../../../components/product-card";
import { useShop } from "../../providers";
import { formatPrice } from "../../../lib/catalog";

export default function ProductDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const { products, addToCart } = useShop(); const product = products.find((item) => item.id === id); const [image, setImage] = useState(0); const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false);
  if (!product) return <main className="inner-page"><div className="empty-state product-missing"><span>☾</span><h2>ไม่พบสินค้านี้</h2><p>สินค้าอาจถูกย้ายหรือยังไม่ได้เผยแพร่</p><Link href="/products" className="primary-button">กลับไปสินค้าทั้งหมด</Link></div></main>;
  const related = products.filter((item) => item.category === product.category && item.id !== product.id).slice(0, 4); const images = product.images?.length ? product.images : ["ปกหน้า", "ด้านหลัง"];
  const add = () => { for (let index = 0; index < quantity; index += 1) addToCart(product); setAdded(true); window.setTimeout(() => setAdded(false), 1800); };
  return <main className="inner-page"><section className="product-detail section"><nav className="breadcrumbs" aria-label="เส้นทางนำทาง"><Link href="/">หน้าแรก</Link><span>/</span><Link href={`/products?category=${encodeURIComponent(product.category)}`}>{product.category}</Link><span>/</span><b>{product.title}</b></nav><button className="back-button" onClick={() => router.back()}>← ย้อนกลับ</button>
    <div className="product-detail-grid"><div className="product-gallery"><div className={`product-main-image ${product.color}`}><span>{product.symbol}</span><b>{product.title}</b><small>{images[image]}</small></div><div className="product-thumbs">{images.map((item, index) => <button className={`${product.color} ${image === index ? "active" : ""}`} key={`${item}-${index}`} onClick={() => setImage(index)}><span>{product.symbol}</span><small>{item}</small></button>)}</div></div>
      <div className="product-summary"><span className="detail-category">{product.category}</span><h1>{product.title}</h1><p className="detail-author">โดย {product.author}</p><div className="detail-price">{product.salePrice && <del>{formatPrice(product.price)}</del>}<strong>{formatPrice(product.salePrice || product.price)}</strong>{product.salePrice && <span>ประหยัด {formatPrice(product.price - product.salePrice)}</span>}</div><p className="detail-description">{product.description}</p>{product.coupon && <div className="detail-coupon"><span>คูปอง</span><b>{product.coupon}</b><small>รับส่วนลดเพิ่มเติมเมื่อชำระเงิน</small></div>}<div className="stock-line"><i /> มีสินค้า {product.stock} ชิ้น</div><div className="detail-actions"><div className="detail-quantity"><button onClick={() => setQuantity((value) => Math.max(1, value - 1))}>−</button><span>{quantity}</span><button onClick={() => setQuantity((value) => Math.min(product.stock, value + 1))}>+</button></div><button className={`detail-add ${added ? "added" : ""}`} onClick={add}>{added ? "✓ เพิ่มลงตะกร้าแล้ว" : "เพิ่มลงตะกร้า"}</button><Link href="/cart" className="buy-now" onClick={add}>ซื้อทันที</Link></div><div className="detail-benefits"><span>◇ จัดส่งฟรีเมื่อครบ ฿1,200</span><span>↻ เปลี่ยนสินค้าได้ภายใน 7 วัน</span><span>♡ คัดสรรและแพ็กด้วยความใส่ใจ</span></div></div>
    </div><div className="product-about"><div><p className="eyebrow">PRODUCT DETAILS</p><h2>เรื่องราวของเล่มนี้</h2></div><p>{product.description} ภายในออกแบบให้ใช้งานง่าย พร้อมแนวทางและตัวอย่างที่คุณสามารถนำไปใช้กับการอ่านไพ่หรือการฝึกปฏิบัติในแต่ละวันได้ทันที</p><dl><div><dt>หมวดหมู่</dt><dd>{product.category}</dd></div><div><dt>ผู้เขียน</dt><dd>{product.author}</dd></div><div><dt>จำนวนคงเหลือ</dt><dd>{product.stock} ชิ้น</dd></div></dl></div>
    {related.length > 0 && <section className="related-products"><div className="section-heading"><div><p className="eyebrow">YOU MAY ALSO LIKE</p><h2>สินค้าในหมวดเดียวกัน</h2></div><Link href={`/products?category=${encodeURIComponent(product.category)}`}>ดูทั้งหมด →</Link></div><div className="book-grid">{related.map((item) => <ProductCard product={item} key={item.id} />)}</div></section>}
  </section></main>;
}
